import { Services } from '../interfaces';

const services: Services = {
  codewars: {
    name: 'codewars',
    link: 'https://www.codewars.com/api/v1/',
    method: 'codewarsApi',
    xlsxField: 'Codewars',
    userParameter: 'users/__target__/code-challenges/completed',
    taskParameter: 'code-challenges/__target__',
    queryParameters: {
      tokenParameter: 'access_key',
      pageParameter: 'page',
    },
    tasks: [
      'opposite-number',
      'printing-array-elements-with-comma-delimiters',
      'basic-mathematical-operations',
      'transportation-on-vacation',
      'get-the-middle-character',
      'partition-on',
      'word-count',
      'remove-first-and-last-character-part-two',
      'implement-a-filter-function',
      'prefill-an-array',
      'cross-product-of-vectors',
      'sequence-generator-1',
      'base-conversion',
      'closures-and-scopes',
      'a-function-within-a-function',
      'can-you-keep-a-secret',
      'using-closures-to-share-class-state',
      'a-chain-adding-function',
      'function-cache',
      'function-composition',
      'function-composition-1',
      'stringing-me-along',
      'i-spy',
      'calculating-with-functions',
      'santaclausable-interface',
      'new-with-apply',
      'extract-nested-object-reference',
      'array-helpers',
      'replicate-new',
      'sum-of-digits-slash-digital-root',
      'fun-with-es6-classes-number-2-animals-and-inheritance',
      'fun-with-es6-classes-number-3-cuboids-cubes-and-getters',
      'lazy-evaluation',
      'tail-recursion-with-trampoline',
      'functional-sql',
      'can-you-get-the-loop',
    ],
    scoreMapping: {
      8: 1,
      7: 1,
      6: 4,
      5: 5,
      1: 20,
    },
  },

  codecademy: {
    name: 'codecademy',
    link: 'https://www.codecademy.com/',
    method: 'codecademyFetch',
    xlsxField: 'Codecademy Login',
    userParameter: '__target__',
    queryParameters: {},
    tasks: [
      'Introduction to HTML',
      'Learn CSS',
    ],
    scoreMapping: {
      'Introduction to HTML': 50,
      'Learn CSS': 50,
    },
  },

  gss: {
    name: 'gss',
    link: '',
    method: 'gssApi',
    queryParameters: {},
  },
};
export default services;
