export { default as TaskCard, type TaskCardProps } from './TaskCard/TaskCard';
export { default as TaskDescription } from './TaskDescription/TaskDescription';
export { default as TaskCardColumn } from './TaskCardColumn/TaskCardColumn';
export { default as TaskDeadlineDate, type TaskDeadlineDateProps } from './TaskDeadlineDate/TaskDeadlineDate';
export { default as VerificationsTable, type VerificationsTableProps } from './VerificationsTable/VerificationsTable';
export { default as Exercise } from './Exercise/Exercise';
export { default as Coding } from './Coding/Coding';
export { default as JupyterNotebook } from './JupyterNotebook/JupyterNotebook';
export { default as SelfEducation } from './SelfEducation/SelfEducation';
export { default as VerificationInformation } from './VerificationInformation/VerificationInformation';
export { default as StatusTabs } from './StatusTabs/StatusTabs';
export { default as AttemptsAnswers } from './AttemptsAnswers/AttemptsAnswers';
