name: 'Publish Test Reports'
on:
  workflow_run:
    workflows: ['Pull Request CI']
    types:
      - completed
jobs:
  test_reports:
    runs-on: ubuntu-latest
    steps:
      - name: Test Report (Client)
        uses: dorny/test-reporter@v1
        with:
          artifact: test-report-client
          name: test report (client)
          path: '*.xml'
          reporter: jest-junit

      - name: Test Report (Server)
        uses: dorny/test-reporter@v1
        with:
          artifact: test-report-server
          name: test report (server)
          path: '*.xml'
          reporter: jest-junit
